#!/bin/bash
########################################################################################################################
# Main control script for running control plane application
########################################################################################################################

# This will controll the form of deployment
export deployment_style=${deployment_style:-DEV}

########################################################################################################################
# Define some functions to be used later

UI_POD_NAME=ui
CP_POD_NAME=cp
W1_PORT=7031
W2_PORT=7032

DEV_MODE_FLAG=

function worker-pod-name () {
  echo "w${1}"
}

function log () {
	if [ -n "$CP_LOG" ]; then
		echo $*
	fi
}

function stop-svc () {
	PID_FILE=$1

	if [ -f "$PID_FILE" ]; then
		PID=$(cat $PID_FILE)
		if [ -n "$PID" ]; then
			NAME=$(ps -q $PID -o comm=)
			if [ -n "$NAME" ]; then
				log "Stopping $NAME ($PID)"
				kill $PID
			fi	
		fi

		rm $PID_FILE
	fi
}

function stop-dev () {
	stop-svc ~/.cp.pid
	stop-svc ~/.ui.pid
	stop-svc ~/.w1.pid
	stop-svc ~/.w2.pid
}

function start-dev () {
	mkdir -p ./log
	
	log "Starting CP Service"
	cp-svr $DEV_MODE_FLAG 2> log/cp.log &
	echo $! > ~/.cp.pid
	sleep 1

	log "Starting UI Service"
	ui-svr $DEV_MODE_FLAG 2> log/ui.log  &
	echo $! > ~/.ui.pid

	log "Starting W1 Service"
	w-svr $DEV_MODE_FLAG --port $W1_PORT  2> log/w1.log &
	echo $! > ~/.w1.pid

	log "Starting W2 Service"
	w-svr $DEV_MODE_FLAG --port $W2_PORT  2> log/w2.log &
	echo $! > ~/.w2.pid
}

########################################################################################################################
# Process command line parameters

while [ -n "$1" ]; do
	case "$1" in
		start)
			OPERATION=start
		;;

		stop)
			OPERATION=stop
		;;

		-d)
			DEV_MODE_FLAG=--dev-mode
		;;

		-l)
			shift
			if [ -z "$1" ]; then
				echo "Missing log level argument to -l (expect trace, debug, info, warn or error)"
				exit 1
			else
				RUST_LOG="${RUST_LOG}${LOG_SEP_CHAR}$1"
				LOG_SEP_CHAR=","
			fi
		;;

		*)
			echo "Unknown parameter $1" 1>&2
			exit 1
		;;
	esac

	shift
done


########################################################################################################################
# Start the application

if [ -n "$OPERATION" ]; then
	case $OPERATION in
	  start)
	    stop-dev  
	    echo "Starting with RUST_LOG=$RUST_LOG"
	    start-dev  
	  ;;
  
	  stop)
	    stop-dev  
	  ;;
  
	  *)
	    echo "Error [$(basename $0)]: unknown operation: ${OPERATION}" >&2
	    exit 1
	  ;;
	esac
else
	echo "No operation defined" 1>&2
	exit 1
fi
