#!/bin/bash
########################################################################################################################
# Main control script for running control plane application
########################################################################################################################

# This will controll the form of deployment
export deployment_style=${deployment_style:-DEV}

########################################################################################################################
# Define some functions to be used later

UI_POD_NAME=ui
CP_POD_NAME=cp
W1_PORT=7031
W2_PORT=7032

function worker-pod-name () {
  echo "w${1}"
}

function log () {
	if [ -n "$CP_LOG" ]; then
		echo $*
	fi
}

function stop-svc () {
	PID_FILE=$1

	if [ -f "$PID_FILE" ]; then
		PID=$(cat $PID_FILE)
		if [ -n "$PID" ]; then
			NAME=$(ps -q $PID -o comm=)
			if [ -n "$NAME" ]; then
				log "Stopping $NAME ($PID)"
				kill $PID
			fi	
		fi

		rm $PID_FILE
	fi
}

function stop-dev () {
	stop-svc ~/.cp.pid
	stop-svc ~/.ui.pid
	stop-svc ~/.w1.pid
	stop-svc ~/.w2.pid
}

function start-dev () {
	mkdir -p ./log
	
	log "Starting CP Service"
	cp-svr 2> log/cp.log &
	echo $! > ~/.cp.pid
	sleep 1

	log "Starting UI Service"
	ui-svr 2> log/ui.log  &
	echo $! > ~/.ui.pid

	log "Starting W1 Service"
	w-svr --port $W1_PORT  2> log/w1.log &
	echo $! > ~/.w1.pid

	log "Starting W2 Service"
	w-svr --port $W2_PORT  2> log/w2.log &
	echo $! > ~/.w2.pid
}

function stop-pods () {
  stop-pod $UI_POD_NAME
  stop-pod $(worker-pod-name 1)
  stop-pod $(worker-pod-name 2)
  stop-pod $CP_POD_NAME
}

function stop-pod () {
  echo "Stopping pod $1"
}

function start-cplane () {
  case ${deployment_style} in
    DEV)
      stop-cplane
      start-dev
    ;;
  
    POD)
      stop-cplane
      start-pod
    ;;
  
    *)
      echo "Error [$(basename $0) start]: unknown deployment style: ${deployment_style}" >&2
      exit 1
    ;;
  esac
}

function stop-cplane () {
  stop-dev
  stop-pods
}

########################################################################################################################
# Process command line parameters

if [ -n "$1" ]; then
  OPERATION=$1
  shift
else
  echo "Error [$(basename $0)]: An operation is required" >&2
  exit -1
fi

########################################################################################################################
# Start the application

case $OPERATION in
  start)
    start-cplane  
  ;;
  
  stop)
    stop-cplane  
  ;;
  
  *)
    echo "Error [$(basename $0)]: unknown operation: ${OPERATION}" >&2
    exit 1
  ;;
esac

