version: "3"

volumes:
  cp_sample_data:
    name: sample
    driver: local

services:
  server:
    name: cp-svr
    image: cplane-base
    network: cplane
    ports:
      - "7201:8000"
      - "3300:3306"
    volumes:
      - cp_sample_data:/var/lib/mysql:Z
    environment:
      - SLEEP_SECS:"600"
      - RUST_LOG:"debug"
  interface:
    name: ui-svr
    image: cplane-ui
    network: cplane
    ports:
      - "7200:8000"
    environment:
      - RUST_LOG:"debug"
