name = "Dashboard"
title = "CPlane Dashboard"
desc = "Main information landing page"
icon = "/static/svg/pages/dashboard.svg"
help = "/static/html/help/dash.html"
css  = ["/static/css/table.css"]
js   = ["/static/js/table.js"]
