name = "Servers"
title = "Server Management"
desc = "Handle managing the servers and resources"
icon = "server.svg"
help = "/static/html/help/dash.html"
css  = ["/static/css/table.css", "/static/css/dash.css" ]
js   = ["/static/js/table.js"]
