name = "Services"
title = "Manage Services"
desc = "Manage services and versions"
icon = "services.svg"
help = "/static/html/help/services.html"
css  = ["/static/css/table.css", "/static/css/services.css"]
js   = ["/static/js/table.js", "/static/js/services.js"]

