#!/bin/bash
########################################################################################################################
## Drop (if it exists) Existing rusty DB and recreates it with initial data
########################################################################################################################

DB_ROOT=$(dirname $0)
DB_NAME=rusty
APP_USER_NAME=rusty_app
APP_USER_PASS=secret

# First, drop the database if it exists
if [ -n "$(echo 'show databases' | sudo mysql | grep $DB_NAME)" ]; then
  echo "Dropping DB $DB_NAME"
  echo "DROP DATABASE $DB_NAME ;" | sudo mysql
fi

# Second, create the DB user
echo "(Re-)creating user $APP_USER_NAME"
echo "CREATE OR REPLACE USER '${APP_USER_NAME}'@'localhost' IDENTIFIED BY '$APP_USER_PASS'" | sudo mysql

# Second, create the DB schema
echo "(Re-)creating DB $DB_NAME"
echo "CREATE DATABASE ${DB_NAME};" | sudo mysql

# Third, grant the DB user all access
echo "Granting user $APP_USER_NAME access on $DB_NAME"
echo "GRANT ALL ON ${DB_NAME}.* TO '${APP_USER_NAME}'@'localhost';" | sudo mysql
echo "GRANT ALL ON ${DB_NAME}.* TO '$(whoami)'@'localhost';" | sudo mysql

# Fourth, create the schema
echo "Initializing the schema on $DB_NAME"
cat $DB_ROOT/cp.create.sql | sudo mysql $DB_NAME

# Finally, insert the sample data
echo "Populating the data in $DB_NAME"
cat $DB_ROOT/cp.sample.insert.sql | sudo mysql $DB_NAME

