#!/bin/bash
########################################################################################################################
# Sync the colorized files with the current files in this directory, substituting in black
########################################################################################################################

for x in *.svg; do
	cp $x black/$x
	cat $x | sed 's/#000000/#d7d78c/' > beige/$x
done
